### ISSUE TITLE
Assertion fails during nlohmann/json tests

### ISSUE THREAD

**Issue by yurivict** [catchorg/Catch2#1241] opened 2018-04-04 19:04 UTC
Tests in https://github.com/nlohmann/json version 3.1.2 fail on FreeBSD due to assertions in catch2: https://github.com/nlohmann/json/issues/1032#issuecomment-378707696

**Comment by nlohmann** [comment] 2018-04-05 05:13
We haven't seen a Catch assertion fail in years - this seems to be an issue related to FreeBSD.

For reference:

```
Assertion failed: (m_parent), function moveToParent, file /usr/ports/devel/nlohmann-json/work/json-3.1.2/test/thirdparty/catch/catch.hpp, line 6222.
```

That's [this line](https://github.com/nlohmann/json/blob/develop/test/thirdparty/catch/catch.hpp#L6222).

Note we are still using Catch v1.9.7 as porting all tests to Catch 2 is still an issue. Nevertheless, it would be interesting to understand what the reported assertion means and if there is a bug somewhere.

**Comment by horenmar** [comment] 2018-04-05 13:03
@yurivict Can you check what happens when you run Catch's self-test on FreeBSD?

**Comment by yurivict** [comment] 2018-04-05 15:47
Yes, there are assertions:
``
loose text artifact
===============================================================================
All tests passed (854 assertions in 142 test cases)
```

Version 2.2.1

**Comment by yurivict** [comment] 2018-05-17 15:30
Now I am trying to update the FreeBSD port ```devel/nlohmann-json``` and Catch is still failing in tests.

Any hope to esolve this?

**Comment by grembo** [comment] 2018-07-29 08:54
This is caused by nlohmann-json using duplicate section names in loops, basically the problem described here: https://github.com/catchorg/Catch2/issues/816#issuecomment-278268122 

You can probably close this issue, as this is not caused by catch, but by an invalid use of it.

**Comment by grembo** [comment] 2018-09-19 22:44
The fix in nlohmann-json has been merged. This is neither a catch2 nor a FreeBSD issue, you can really close it now.

**Comment by horenmar** [comment] 2018-09-20 16:21
I have been a bit busy so I didn't notice that it has been resolved since.

Thank you for reporting back.

**Closed by horenmar** 2018-09-20 16:21 UTC
Labels: Possible bug
