### ISSUE TITLE
REQUIRE behaves badly with un-parenthesized expressions containing commas

### ISSUE THREAD

**Issue by ldionne** [catchorg/Catch2#860] opened 2017-03-16 21:57 UTC
## Description
Using initializer lists or other non-parenthesized expressions including commas inside the `REQUIRE` macro triggers a compilation error.

## Steps to reproduce
The following does not compile:

```c++
#include <vector>

TEST_CASE("foo") {
  REQUIRE(std::vector<int>{1, 2} == std::vector<int>{1, 2});
}
```

The error is

```
prog.cc:11350:59: error: macro "REQUIRE" passed 3 arguments, but takes just 1
   REQUIRE(std::vector<int>{1, 2} == std::vector<int>{1, 2});
                                                           ^
prog.cc: In constructor 'Catch::FatalConditionHandler::FatalConditionHandler()':
...
```

The issue is likely that `REQUIRE` is not defined as a variadic macro, but it should be possible to change that. Example on Wandbox: http://melpon.org/wandbox/permlink/zsRrQwDpmMYleTIb (scroll to the bottom).

**Comment by nabijaczleweli** [comment] 2017-03-16 22:07
Think about [your](https://github.com/philsquared/Catch/issues/725#issuecomment-253290361) [actions](https://github.com/philsquared/Catch/issues/431#issuecomment-106918543).

**Comment by ldionne** [comment] 2017-03-17 04:24
I apologize if I didn't take the time to look through the [50 issues](https://github.com/philsquared/Catch/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20REQUIRE) containing the keyword `REQUIRE` before opening this. I actually did that consciously knowing I might open a duplicate, since it takes about 10 seconds for the maintainer to spot that it's a duplicate.

And anyway, the the two issues you link to are marked as closed (yet the issue is not resolved at all), so what the hell? So in spite of being witty, you haven't done anything useful yet and told me why using variadic macros can't solve this.

**Comment by ldionne** [comment] 2017-03-17 04:28
IOW, I shouldn't have to use parentheses like you suggested on the two issues you linked; the library should be fixed to support this common use case unless there's a reason why it can't be implemented, in which case you ought to explain what it is and I'll be satisfied.

**Comment by philsquared** [comment] 2017-03-17 06:50
Hi @ldionne, and welcome to Catch :-)
Thanks for bringing this up (yes, again!). Your proposal is something I've thought about in the past but not had time to investigate properly. It's a little involved to try out because the `REQUIRE` macro forwards on to an internal macro that takes additional arguments afterwards. These can be reordered, but that's going to ripple out to dozens of other macros. Then it all has to be duplicated for the case where variadic macros are not supported.
It's all doable, and I believe will work - and now I'm getting a bit more time to spend on Catch I'll give it a go (when I get back from the current conference I'm at) - so thanks for reminding me of this.

**Comment by kirbyfan64** [comment] 2017-03-17 15:48
> And anyway, the two issues you link to are marked as closed (yet the issue is not resolved at all), so what the hell? So in spite of being witty, you haven't done anything useful yet and told me why using variadic macros can't solve this.

Man, you took that waaaay too seriously​...

**Comment by ldionne** [comment] 2017-03-17 16:16
@philsquared Now, that's something I can understand, thanks a lot! I suggest we leave this open so as to not pretend that the issue is fixed, but feel free to fix it or not. I might have a shot at it too if I get some time.

@kirbyfan64 
> Man, you took that waaaay too seriously​...

Yes, probably, but I became pretty hostile to the guy when I read [his comment](https://github.com/philsquared/Catch/issues/725#issuecomment-253290361) on a previously closed issue for the same problem (which might have been a joke too, but at some point you need to draw the line).

**Comment by kirbyfan64** [comment] 2017-03-17 19:18
True, but FWIW a lot of people in European countries (not sure if Poland is included) tend to be more blunt culturally than in the U.S.

**Comment by nabijaczleweli** [comment] 2017-03-17 19:49
You know what? I typed up a really long and detailed response about how your complete lack of respect for the maintainers' time could be circumvented by thinking for more than 3 seconds, but I gave up. So here, take this imaginary badge as a token of defeating even my will to reason with.

**Comment by ldionne** [comment] 2017-03-17 19:55
> people in European countries (not sure if Poland is included) tend to be more blunt culturally than in the U.S

I'm Canadian, so I guess the gap might be even larger! :)

@nabijaczleweli Sorry for being a bit harsh; I just disliked your answer to the issue, which I perceived as being blunt (even as [a maintainer myself](https://github.com/boostorg/hana)). That's it, now let's stop fighting on this completely inappropriate forum.

**Comment by horenmar** [comment] 2017-03-18 11:04
@nabijaczleweli Especially your second comment isn't really helping.

Anyway, I am really busy this month so I'll happily leave this to Phil.

**Comment by philsquared** [comment] 2017-03-21 13:41
I've made the prerequisite changes (changing the macro argument order), which was a bit of a pain but just a mechanical change. I think I prefer it that way anyway. I've committed that as: f3ec843ba6513b496f3fb384732c2cdd0bedea11.

I then made just enough changes, locally, to get @ldionne's example work using variadic macros. That was fairly simple and seemed to work well.
The problem is, now, writing all the variadic/ non-variadic versions - which will double up quite a few macros, including some non trivial ones.

At this point I'm out of time for a couple of weeks so will have to put this on pause - but if anyone else wants to pick this up it should be fairly obvious what needs to be done now - just be sure to check with a compiler that doesn't support variadic templates, as well as with the `CATCH_CONFIG_FAST_COMPILE` and CATCH_CONFIG_PREFIX_ALL flags.

**Comment by onqtam** [comment] 2017-03-22 13:42
I just implemented this in doctest in the dev branch - see [this commit](https://github.com/onqtam/doctest/commit/07f027dae8747e3532f6f04c2693a13e9d77d390)

online demo: [wandbox](http://melpon.org/wandbox/permlink/vyaFqgLoLhw0iFeP)

I managed to reuse most of my macro internals by packaging the ```__VA_ARGS__``` as a single parameter with extra parenthesis in the interface macros - like [this](https://github.com/onqtam/doctest/commit/07f027dae8747e3532f6f04c2693a13e9d77d390#diff-7da89be163d7a0933a87f2d9beb555d7R1399) (so ```DOCTEST_ASSERT_PROXY``` doesn't get changed at all - it forwards to ```DOCTEST_ASSERT_IMPLEMENT``` the packaged variable arguments) - and later remove the parenthesis - like [this](https://github.com/onqtam/doctest/commit/07f027dae8747e3532f6f04c2693a13e9d77d390#diff-7da89be163d7a0933a87f2d9beb555d7R1379)

**Comment by horenmar** [comment] 2017-04-25 19:30
@ldionne Can you check whether the attached single include works for you? It should accept commas in expressions in most assertion macros. Only the ones that need more than 1 arguments (ie `REQUIRE_THROWS_AS`) are not supported ATM.
[catch.zip](https://github.com/philsquared/Catch/files/956293/catch.zip)

**Comment by philsquared** [comment] 2017-04-26 15:18
Sorry, @ldionne, looks like that header was not quite sufficient.
The attached should do it, though.

[catch.hpp.zip](https://github.com/philsquared/Catch/files/958890/catch.hpp.zip)

(btw, time sensitive, but I'm at the ACCU conference at the moment, so do come and say "hi" at the JetBrains booth - if you get this in time :-) )

**Comment by ldionne** [comment] 2017-04-27 10:29
Yes, that solves my problem! Thanks a lot!

**Comment by philsquared** [comment] 2017-04-27 10:44
Excellent! Thanks for letting us know.
The Catch2 branch should go live in the near future!

**Comment by horenmar** [comment] 2017-11-03 14:44
Catch 2 is live

**Closed by horenmar** 2017-11-03 14:44 UTC
Labels: In progress, Tweak request
