### ISSUE TITLE
Catch2 Builds as Shared library when parent CMake sets `BUILD_SHARED_LIBS`

### ISSUE THREAD

**Issue by AidanBeltonS** [catchorg/Catch2#2895] opened 2024-08-06 13:47 UTC
**Describe the bug**
Catch 2 builds its libraries as a shared library, when using `BUILD_SHARED_LIBS=ON` and pulling the repo via `FetchContent`.

**Expected behavior**
It seems the v3 library is supposed to work only as a static library. Correct me if I am wrong. So regardless of the project that uses Catch2, the Catch2 library should build as a static not shared library.

If this is expected behaviour, please close this issue.

**Reproduction steps**
```
$ git clone https://github.com/AidanBeltonS/Catch2_reproducer
$ cd Catch2_reproducer
$ mkdir build
$ cd build
$ cmake -G Ninja .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
$ ninja
$ find -name "*.so"
./_deps/catch2-build/src/libCatch2Main.so
./_deps/catch2-build/src/libCatch2.so
./libMain_Object.so
```

**Additional context**
I have not encountered any specific problem with it being a shared library, however it seems like an error to have the parent CMake effect the Catch build in this way.

**Comment by horenmar** [comment] 2024-08-17 12:45
Catch2 can be built as a shared lib, but I don't try to support it past using CMake-provided utility to make every symbol visible -> if that fails, the user is on their own.

As for `BUILD_SHARED_LIBS`, Catch2 tries to use the standard CMake configuration options. This does mean that if you include it as a subproject, it will use the same configuration, because it is global. If you need something different, you have to undo it yourself.

**Comment by ChrisThrasher** [comment] 2024-09-24 20:24
Closing as this is the intended behavior of the library and a natural side effect of the way FetchContent works.

**Closed as completed by ChrisThrasher** 2024-09-24 20:24 UTC
