### ISSUE TITLE
toString self-tests failing with MSVC2013

### ISSUE THREAD

**Issue by RossBencina** [catchorg/Catch2#575] opened 2016-01-20 14:18 UTC
Current master is failing the following two tests when built with MSVC2013:

```
SelfTest.exe is a Catch v1.3.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
toString( vectors<has_toString )
-------------------------------------------------------------------------------
C:\catch\Catch-test\projects\SelfTest\ToStringWhich.cpp(52)
...............................................................................

C:\catch\Catch-test\projects\SelfTest\ToStringWhich.cpp(55): FAILED:
  REQUIRE( Catch::toString( v ) == "{ {?} }" )
with expansion:
  "{ toString( has_toString ) }" == "{ {?} }"

-------------------------------------------------------------------------------
toString( vectors<has_maker_and_toString )
-------------------------------------------------------------------------------
C:\catch\Catch-test\projects\SelfTest\ToStringWhich.cpp(64)
...............................................................................

C:\catch\Catch-test\projects\SelfTest\ToStringWhich.cpp(67): FAILED:
  REQUIRE( Catch::toString( v ) == "{ StringMaker<has_maker_and_toString> }" )
with expansion:
  "{ toString( has_maker_and_toString ) }"
  ==
  "{ StringMaker<has_maker_and_toString> }"

===============================================================================
test cases: 100 |  98 passed | 2 failed
assertions: 630 | 628 passed | 2 failed
```

**Comment by snaewe** [comment] 2016-09-16 19:00
FWIW, I can confirm this. If I apply this commit 
snaewe@020580626ae56d3377f5c62b002ba3906a4d3edc the test succeeds with MSVC2013, mingw gcc-6.1 (both on Win7), and gcc 4.8.4 on Linux.

**Comment by horenmar** [comment] 2017-01-17 09:12
Same goes with for MSVC 2015.

**Comment by horenmar** [comment] 2018-02-14 21:30
IIRC this was a problem with 2-phase lookup in MSVC that couldn't be quite fixed. Since Catch2 no longer uses `toString` and thus does not have this problem (and fully updated MSVC 2017 support 2-phase lookup!), I am going to close this.

**Closed by horenmar** 2018-02-14 21:30 UTC
Labels: Inconvenient bug
