### ISSUE TITLE
CATCH_CONFIG_MAIN always exits with 0 causing ctest to think that failing tests have passed.

### ISSUE THREAD

**Issue by owo** [catchorg/Catch2#1221] opened 2018-03-11 13:16 UTC
## Description
When using Catch with cmake/ctest, running `make test` reports all tests have passed even when a test should fail. This is due to CATCH_CONFIG_MAIN returning 0 when exiting even though the compiled test program reports there was a failure. I think in order to make Catch more compatible with ctest and other test tools, it should exit with a non-zero return code (perhaps return with the number of failed test cases?).

Note: I only tried this with BDD-style tests.

### Steps to reproduce
I created a [small repo](https://github.com/owo/catch_cmake_test) that will reproduce the problem.
The README contains instructions for running it.

### Extra information
* Catch version: **v2.2.0**
* Operating System: **macOS 10.13.3**
* Compiler+version: **Apple LLVM version 9.0.0 (clang-900.0.37)**

**Comment by horenmar** [comment] 2018-03-11 13:43
Duplicate of #1215 -> Fixed in [v2.2.1] https://github.com/catchorg/Catch2/releases/tag/v2.2.1

**Closed by horenmar** 2018-03-11 13:43 UTC

**Comment by owo** [comment] 2018-03-11 13:49
Thanks. For some reason git didn't pull the latest version.
