### ISSUE TITLE
Disabling signals is broken

### ISSUE THREAD

**Issue by Leandros** [catchorg/Catch2#1295] opened 2018-05-25 11:51 UTC
Signals cannot be disabled, since if the macro `CATCH_CONFIG_POSIX_SIGNALS` is defined, signals are enabled, and if the macro is not defined, it is getting defined automatically.

**Comment by onqtam** [comment] 2018-05-25 13:04
have you tried defining ```CATCH_CONFIG_NO_POSIX_SIGNALS```?

**Comment by Leandros** [comment] 2018-05-25 13:27
Yes

**Comment by BiCapitalization** [comment] 2018-05-27 21:04
I can't reproduce the issue. What platform are you on? Could you write up a minimal example?

**Comment by horenmar** [comment] 2018-07-04 12:28
Since there has been no followup, I am going to close this.

**Closed by horenmar** 2018-07-04 12:28 UTC
Labels: Can't reproduce

**Comment by Leandros** [comment] 2018-07-05 19:14
`driver.cc`:

```
#undef TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
#define CATCH_CONFIG_IMPL_ONLY
#define CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_NO_POSIX_SIGNALS
#define CATCH_INTERNAL_CONFIG_NO_POSIX_SIGNALS
#include <catch.hpp>
#include <catch_reporter_teamcity.hpp>

int main(int argc, char **argv)
{
    Catch::Session session;
    int ret = session.applyCommandLine(argc, argv);
    if (ret != 0)
        return ret;
    return session.run();
}
```

Simple as that. Than write a test which does a nullptr access and observe how 

```
 failed: fatal error condition with message: 'SIGSEGV - Segmentation violation signal'
```

is still printed.

**Comment by Leandros** [comment] 2018-07-05 19:43
Alright, I figured out that catch is using VEH (not actually SEH, as the macro might suggest) to print the mentioned message. Disabling it via the macro also now prevents the message. However, if doesn't call my SEH handler. Do you still have some "global" try catch around everything?

**Comment by jdoubleu** [comment] 2021-09-23 13:33
I'm currently facing the same issue: Although I defined `CATCH_CONFIG_NO_POSIX_SIGNALS`, `CATCH_CONFIG_POSIX_SIGNALS` is still set.

My `main.cpp` looks something like:
```cpp
#define CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_DISABLE_EXCEPTIONS
#define CATCH_CONFIG_NO_POSIX_SIGNALS
#include <catch2/catch_all.hpp>

void app_main() {
  // code ...
  Catch::Session().run();
}
```

I'm on the latest `devel` branch and targeting a different architecture than x86, arm and a different platform than linux or windows.

I'm also including Catch2 from a subdirectory, as mentioned [here](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#cmake-targets). In this setup, the `.cpp` files are separately built and linked to my target, thus they do not include my configuration. When I'm forcefully add this definition through CMake, it works:
```CMake
// ...
add_subdirectory(thirdparty/Catch2)
target_compile_definitions(Catch2 PUBLIC
        CATCH_CONFIG_NO_POSIX_SIGNALS)
        
// ...
target_link_libraries(my_app PRIVATE Catch2::Catch2
```
