### ISSUE TITLE
Missing symbols For GCC 9 on MacOS Mojave

### ISSUE THREAD

**Issue by wagoner47** [catchorg/Catch2#1629] opened 2019-05-13 20:40 UTC
**Describe the bug**
Trying to compile test code with single-header version of Catch generates an error for undefined symbol(s), apparently related to std::ostringstream. I've tried installing Catch instead, with no difference. This had been working on GCC 8, but now fails to compile with GCC 9.

I've tried testing this by compiling and running the first example from the tutorial (010-TestCase.cpp), and I instead have an undefined symbol related to std::stringstream. The error message below is from running on the example test.

I don't know if this is at all related to Issue #1591 

**Expected behavior**
```
010-TestCase.cpp:14: failed: Factorial(0) == 1 for: 0 == 1
010-TestCase.cpp:18: passed: Factorial(1) == 1 for: 1 == 1
010-TestCase.cpp:19: passed: Factorial(2) == 2 for: 2 == 2
010-TestCase.cpp:20: passed: Factorial(3) == 6 for: 6 == 6
010-TestCase.cpp:21: passed: Factorial(10) == 3628800 for: 3628800 (0x375f00) == 3628800 (0x375f00)
Failed 1 test case, failed 1 assertion.
```

**Reproduction steps**
Steps to reproduce the bug: Compiled as in the tutorial, but replacing CATCH_SINGLE_INCLUDE with the path to my include directory
```
g++-9 -std=c++11 -Wall -I/usr/local/include -o 010-TestCase 010-TestCase.cpp && 010-TestCase --reporter compact --success
```

**Platform information:**

 - OS: **MacOS Mojave 10.14.4**
 - Compiler+version: **Homebrew GCC v9.1.0**
 - Catch version: **v2.7.2**

**Additional context**
Error message when running on tutorial example: 
```
Undefined symbols for architecture x86_64:
  "std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()", referenced from:
      Catch::clara::detail::BasicResult<Catch::clara::detail::ParseResultType> Catch::clara::detail::convertInto<unsigned int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&) in ccX50X5i.o
      Catch::clara::detail::BasicResult<Catch::clara::detail::ParseResultType> Catch::clara::detail::convertInto<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&) in ccX50X5i.o
  "std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()", referenced from:
      Catch::clara::detail::Opt::getHelpColumns() const in ccX50X5i.o
      Catch::StringStreams::add()     in ccX50X5i.o
      Catch::TablePrinter::TablePrinter(std::basic_ostream<char, std::char_traits<char> >&, std::vector<Catch::(anonymous namespace)::ColumnInfo, std::allocator<Catch::(anonymous namespace)::ColumnInfo> >) in ccX50X5i.o
      Catch::StringStreams::StringStreams() in ccX50X5i.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Comment by horenmar** [comment] 2019-06-10 18:27
Can you try placing `#include <sstream>` at the top of the cpp file? I suspect the problem is that the new version of libstdc++ rejiggered some functions around the std headers.

**Comment by Michael137** [comment] 2020-04-26 14:57
Getting this too on Clang 11 MacOS Catalina

**Comment by horenmar** [comment] 2020-05-15 13:28
@Michael137 Did you try adding `#include <sstream>`?

**Comment by horenmar** [comment] 2021-08-22 19:21
Closing this due to a lack of followup.

**Closed by horenmar** 2021-08-22 19:21 UTC
Labels: Possible bug
