### ISSUE TITLE
Bug: Abuse of the exit code

### ISSUE THREAD

**Issue by rakhimov** [catchorg/Catch2#1146] opened 2018-01-12 06:09 UTC
## Description

It is *nasty* to abuse exit codes in environment where exit codes are specifically for **errors**.
It doesn't compose or play well with every other command line tools.
If you need to count things, have '--count' flag (e.g, git) that reports to stdout.

It doesn't seem to be documented currently,
but exit codes are limited in range to MaxExitCode (=255).
This is just another smell.

### Steps to reproduce

```bash
set -e
set -o pipefail

catch_main --list-test-names-only | wc -l
```

or

```
# No way to specify memory leak return code. Catch can return 127 as well!
valgrind --tool=memcheck --error-exitcode=127 catch_main
```
### Extra information

* Catch version: **v2.1**
* Operating System: **GNU/Linux**
* Compiler+version: **GCC, Clang**

**Comment by horenmar** [comment] 2018-01-12 11:08
There are basically three points in this

1) Returning the number of tests/reporters etc. in return code is weird and unexpected

This one I agree with, but because of backward compatibility is very likely here to stay.

2) Catch shouldn't use the number of failed tests as return code.

This one I don't agree with. Tests failing is an error. If you care that you cannot tell whether you have XYZ failing tests or are leaking memory, you care about the wrong problem.

3) Clamping the return code is weird.

Blame POSIX. Both `waitid` and `waitpid` only keep lowest 8 bits of process return value, so a return value in the multiple of 256 would lead to a false positive otherwise.


Anyway, 1) and 2) can [be easily solved by defining your own main function](https://github.com/catchorg/Catch2/blob/master/docs/own-main.md#let-catch-take-full-control-of-args-and-config), that returns different exit codes.

**Comment by philsquared** [comment] 2018-01-12 13:20
FTR I agree with everything @horenmar says. WRT (1) it was a case of "seemed like a good idea at the time".
I don't know if anyone really relies on it - but if they do it's not many. We should probably have changed it in the move to Catch2, but we could do it on the next major version?

And finally I'll add that (3) can also be addressed by providing your own `main()` - as long as your platform supports the unclamped values (e.g. Windows). I'm not sure how useful it really is in practice, though (if you have more than 255 tests failing do you really care about the exact number?)

**Closed** 2018-02-08 11:07 UTC
Labels: Won't Fix

**Comment by Bu11etmagnet** [comment] 2018-02-15 10:57
Returning nonzero when tests fail is very useful (I'd say required) when running tests from a build system.
Let's hope nobody will have 256 (or multiples of it) test failures, because it would look like success.

**Comment by philsquared** [comment] 2018-02-15 11:25
The return value is clamped to 255 - so if 256 tests fail the return value will be 255. It won't look like success.

**Comment by hpesoj** [comment] 2019-09-24 14:49
> 2. Catch shouldn't use the number of failed tests as return code.
> 
> This one I don't agree with. Tests failing is an error. If you care that you cannot tell whether you have XYZ failing tests or are leaking memory, you care about the wrong problem.

I strongly disagree. A non-zero exit code should indicate that the program did not run as intended. I care that I cannot tell the difference between "the tests did not run as intended" and "the tests did not pass". The test report is for reporting the outcome of the tests.

My real-life use case is a GitLab pipeline that runs a unit test job. If any tests fail, the executable returns a non-zero exit code, and GitLab interprets this as a "script failure" and aborts the job without even processing the test report. This is not what I want, so I have to silence the error by appending `|| true` to the command. But now if my tests actually fail to run, GitLab will proceed, only to fail later when it discovers the test report is missing. GitLab is behaving correctly, as it has no way to distinguish between test failures and genuine script failures. Catch2 is indeed misusing the exit codes.

I understand that the default behaviour cannot be changed until the next major version, but as a temporary solution, it would be great to be able to define a preprocessor flag to disable the use of exit codes for non-error conditions.

**Comment by ddomnik** [comment] 2023-04-04 12:26
I agree with the thread starter. For me, I run the tests in a powershell script, which ofc should handle exceptions of other calls. A failed test case is not the same a failed execution error (e.g. calling the catch2 with an invalid argument).

However, as far as I noticed, a script error will always return exit code 255? If so, I have to hope that there is no unit test with 255 test cases.
