### ISSUE TITLE
Catch::Matchers::Contains("string") does not compile after migration (with catch_all.hpp)

### ISSUE THREAD

**Issue by syberrus** [catchorg/Catch2#2131] opened 2020-12-24 20:15 UTC
**Describe the bug**
Catch::Matchers::Contains("string") (and possibly others) does not compile when "catch2/matchers/catch_matchers_contains.hpp" is included

**Reproduction steps**

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_contains.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
// OR #include <catch2/catch_all.hpp>

...
CHECK_THAT(std::string("hello"), Catch::Matchers::Contains( "hello" ));

This won't compile.
Because in "catch_matchers_contains.hpp" there is template Contains() function overload that grabs everything when args dont match exactly.
Exact string match is only Contains(const std::string&) which is not a case for tests.
So that the above code creates container matcher which is trying to match a char against character array

This issue makes it impossible to migrate to v3 by just replacing include catch.hpp with include catch_all.hpp (as well as simply including catch_matchers_all.hpp)

**Comment by syberrus** [comment] 2021-01-20 16:04
hello?

**Comment by pr0g** [comment] 2021-02-22 22:17
I ran into this too.

It's reproducible by adding `#include <catch2/matchers/catch_matchers_contains.hpp>` to `tests/SelfTest/UsageTests/Matchers.tests.cpp` when building with `-DCATCH_DEVELOPMENT_BUILD=ON`.

I had a quick mess around with adding some more SFINAE type traits to the `Contains` calls but didn't have much luck, unfortunately. I think I got the matches to strings to be ignored using an `is_string` type trait:

```c++
template<typename T>
struct is_string
    : public disjunction<
            std::is_same<char *, typename std::decay_t<T>>,
            std::is_same<const char *, typename std::decay_t<T>>,
            std::is_same<std::string, typename std::decay_t<T>>
    > {
};
```
But then ran into a similar problem with the `Contains` call when dealing with containers (e.g. `std::vector`). Someone with more template metaprogramming experience might have more luck. I'll try and have another crack at some point.

**Comment by horenmar** [comment] 2021-03-22 20:30
Universal/forwarding references strike again.

Originally I thought that the problem could be temporarily fixed by explicitly converting the argument to `Contains` to a `std::string`, e.g. using a literal. However, it turns out that is not enough, as an rvalue of `std::string` prefers `T&&` overload to `std::string const&` overload, and the same goes for most variants, see this:

```cpp
#include <iostream>
#include <string>

void overloaded(std::string const& str) {
    std::cout << "str const&\n";
}

template <typename T>
void overloaded(T&& t) {
    std::cout << "T&&\n";
}

using namespace std::string_literals;

int main() {
    std::string lval;
    std::string const& clref = "ddd"s;
    std::string& lref = lval;
    
    overloaded(lval);  // T&&
    overloaded(clref); // str const&
    overloaded(lref);  // T&&
    overloaded(std::string{}); // T&&
}
```

There is also no reasonable way to SFINAE away the "wrong" overload, as both overloads make sense when dealing with `std::string`. The range overload makes sense when the lhs is something like `std::vector<std::string>`, while the string overload makes sense when the lhs is `std::string`, and there is no way to detect which of these is the case when the overload is being selected. (And even if there was a way to fix that, it would probably be too much magic).


The end result is that the `Contains(std::string const&, CaseSensitive)` overload needs to be renamed to avoid clashing with the generic range overload.

**Comment by pr0g** [comment] 2021-03-25 09:59
Thanks very much for the follow-up @horenmar!

I'm glad I wasn't being completely blind and missed something obvious.

Is the fix then ultimately just a rename? I take it the devel branch doesn't care so much about breaking changes?

Thanks!

Tom

**Closed as completed** 2021-09-27 19:55 UTC
Labels: Serious bug

**Comment by pr0g** [comment] 2021-09-27 21:22
Amazing! Thank you @horenmar very much for fixing this, much appreciated 😄

**Comment by RL-S** [comment] 2021-11-08 17:09
Omg, googled this issue for hours, finally found this! Thank you for providing the workaround!
