### ISSUE TITLE
Not working hidden test tags

### ISSUE THREAD

**Issue by a-suresh** [catchorg/Catch2#1309] opened 2018-06-08 09:54 UTC
## Description
When we add the tags like [.][test1] in the test case1, the test case 1 should not run by default. But I see the test case 1 is running

### Steps to reproduce
Added the `[.] ` in the tags of test case definition. 
And enable the same in the cmake file(**ParseAndAddCatchTests.cmake)**
`option(PARSE_CATCH_TESTS_NO_HIDDEN_TESTS "Exclude tests with [!hide], [.] or [.foo] tags" ON)`
Run the test case using ctest in the jenkins integration. It is running the test cases which has tags as [.]
### Extra information

* Catch version: **v2.2.2**
* Operating System:(Ubuntu 5.4.0-6ubuntu1~16.04.9)
* Compiler+version: gcc  5.4.0 20160609

**Comment by a-suresh** [comment] 2018-06-08 10:13
@philsquared I have enabled the debug logs by enable the flag in `ParseAndAddCatchTests.cmake` 
`option(PARSE_CATCH_TESTS_VERBOSE "Print Catch to CTest parser debug messages" ON)`

When I run locally using ctest, I am able to get the debug messages. But when I run using ctest integrating with jenkins, not getting debug messages.

**Comment by horenmar** [comment] 2018-06-10 18:29
So, your problem is not with Catch, but with the parsing script.

You will need to provide a minimal reproducible example, because I just took the `ParseAndAddCatchTests` from master, compiled this sample application

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.2)
project(test LANGUAGES CXX VERSION 0.0.1)

# Force C++11, also disable GNU extensions
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(tests empty.cpp)


include(CTest)

set(PARSE_CATCH_TESTS_NO_HIDDEN_TESTS ON)
set(PARSE_CATCH_TESTS_VERBOSE ON)

include(ParseAndAddTests.cmake)
ParseAndAddCatchTests(tests)
```
```cpp
// empty.cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("foo1", "[.][test1]") {
    SUCCEED();
}
```

against Catch v2.2.2 and it worked as intended (there were no tests registered with CTest).

**Comment by horenmar** [comment] 2018-07-04 12:10
Without followup I am going to close this soon.

**Closed** 2019-01-25 20:30 UTC
Labels: Can't reproduce, Resolved - pending review
