### ISSUE TITLE
Multi-line string literals in TEST_CASE name causes multiple separate tests to be executed that always pass.

### ISSUE THREAD

**Issue by tomvierjahn** [catchorg/Catch2#1652] opened 2019-06-05 20:01 UTC
**Describe the bug**
Long test names are split into multi-line string literals, e.g., by clang-format, or due to style requirements. This lets Catch create multiple tests -- one per line of the multi-line string literal. These tests always pass even when having a `REQUIRE(false);` in it.

**Expected behavior**
One test is produced even for multi-line test names. This test passes/fails correctly.

**Reproduction steps**
Code:
```c++
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

TEST_CASE("This is a one-line test title", "[tag][.]") { REQUIRE(false); }
TEST_CASE(
    "This is a longer one-line test title that has the tags in a new line",
    "[tag][.]") {
  REQUIRE(false);
}
TEST_CASE(
    "This is a much longer test title that spans two lines and uses standard "
    "multi-line string syntax",
    "[tag][.]") {
  REQUIRE(false);
}
TEST_CASE(
    "This is a still way much longer test title that spans three lines and "
    "uses standard multi-line string syntax -- this is just some placeholder "
    "text to reach the third line",
    "[tag]") {
  REQUIRE(false);
}
```
Note: Tags `[.]` are used to have only a single test being executed.

Output:
```bash
    Start 1: This is a still way much longer test title that spans three lines and uses
1/9 Test #1: This is a still way much longer test title that spans three lines and uses ...   Passed    0.00 sec
    Start 2: standard multi-line string syntax -- this is just some placeholder text to
2/9 Test #2: standard multi-line string syntax -- this is just some placeholder text to ...   Passed    0.00 sec
    Start 3: reach the third line
3/9 Test #3: reach the third line .........................................................   Passed    0.00 sec
```
Note: This is example was created in a larger test suite -- therefore 9 tests in total.

**Platform information:**
 - OS: macOS 10.14.5
 - Compiler+version: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
 - Catch version: catch2: stable 2.8.0 (bottled) -- installed via homebrew

**Additional context**
CMakeLists.txt (in a subdirectory with `enable_testing()` in the project root's CMakeLists.txt):
```cmake
find_package(Catch2 REQUIRED)

add_executable(tests
  src/main.cpp
  )
target_link_libraries(tests Catch2::Catch2)

include(CTest)
include(Catch)
catch_discover_tests(tests)
```

**Comment by horenmar** [comment] 2019-06-06 13:15
I strongly suspect that this would work if you passed the names directly to the Catch binary, but the problem is that `catch_discover_tests` does not properly handle the possibility of the output wrapping on multiple lines.

**Comment by horenmar** [comment] 2019-06-06 14:56
Yeah, this is a duplicate of #1645.

**Closed by horenmar** 2019-06-06 14:56 UTC
Labels: Contrib, Duplicate
