### ISSUE TITLE
Catch2 Performance

### ISSUE THREAD

**Issue by coombez** [catchorg/Catch2#1086] opened 2017-11-08 21:12 UTC
Took a quick look at Catch2 today.  I'll need to spend some time on its performance before I'll be able to adopt Catch2 for our code base.  It looks like it has some significant performance regressions over Catch1.

Here is the test case for Catch1 and Catch2:

```c++
for(uint64_t i = initial ; i < initial + 1000000000; ++i)
    CHECK(i != reinterpret_cast<uint64_t>(&f));
```

Here's a reasonable benchmark for how long an assertion should take:

```cpp
for(uint64_t i = initial ; i < initial + 1000000000; ++i)
    if(!(i != reinterpret_cast<uint64_t>(&f)))
    {
        ++failed;
        throw "Do Reporting";
    }
    else
    {
        ++passed;
        if(report_non_failure)
            throw "Do Reporting";
    }
```

f is some function, this just makes sure the check doesn't get completely optimized away.  initial is just a value used if you happen to hit the value of the function address.  report_non_failure is a bool that indicates whether even successful checks should be reported.  passed and failed are counters.  The throw's are just substitutes for all the beautiful reporting Catch does :)

Catch2 test: 2m51.072s
Catch1 test: 0m28.460s
reasonable benchmark: 0m00.453s

**Comment by coombez** [comment] 2017-11-09 15:29
Forgot to mention I ran the Catch2 test above through prof as well.  Despite being compiled with full optimization it looks like most of the functions were not being inlined.  Trivial stuff like Catch::isTrue, and the StringRef constructors and destructors consumed 10s of percent of runtime.  Experimentally I was able to fix a few by adding the inline keyword and moving them closer to the beginning of the single include file.

**Comment by horenmar** [comment] 2017-11-09 15:34
That is definitely a pretty bad regression.

Anyway, I did some quick profiling under MSVC and so far
 * MSVC says that `std::string` construction takes about 5% of total time spent in `Catch::AssertionHandler::handle`. A quick look says that we pointlessly copy `std::string` because of `AssertionResultData`.
```cpp
    struct AssertionResultData
    {
        AssertionResultData() = delete;

        AssertionResultData( ResultWas::OfType _resultType, LazyExpression const& _lazyExpression );

        std::string message;
        mutable std::string reconstructedExpression;
        LazyExpression lazyExpression;
        ResultWas::OfType resultType;

        std::string reconstructExpression() const;
    };

...
    void AssertionHandler::handle( AssertionResultData const& resultData, ITransientExpression const* expr ) {

        getResultCapture().assertionRun();

        AssertionResult assertionResult{ m_assertionInfo, resultData }; // <- String copy because resultData
        assertionResult.m_resultData.lazyExpression.m_transientExpression = expr;

        getResultCapture().assertionEnded( assertionResult ); // <- At least 1 another string copy

        if( !assertionResult.isOk() ) {
            m_shouldDebugBreak = getCurrentContext().getConfig()->shouldDebugBreak();
            m_shouldThrow =
                    getCurrentContext().getRunner()->aborting() ||
                    (m_assertionInfo.resultDisposition & ResultDisposition::Normal);
        }
    }
```
There are other pointless copies caused by the `std::string` member in `AssertionResultData` and handling of other assertions, but those are 1 at most.
*  Another 25% of time is spent inside `m_reporter->assertionEnded` of console reporter (I ran the default). This is another place where `std::string` is copied needlessly, but not that much. All in all, it seems like a case of death by a thousand cuts.

**Comment by coombez** [comment] 2017-11-09 15:41
There is definitely no hope of just squeezing all the thousand places.  I suspect the only strategy that will work is complete avoidance of doing any work in the case that no results will be reported.  If done right, I truly believe the 2 billion checks per second number is achievable, although the restructuring required is likely significant.

**Comment by philsquared** [comment] 2017-11-09 16:33
> complete avoidance of doing any work in the case that no results will be reported
We've actually done quite a lot here already. Clearly there is more to be done - but what interests me is where the regression is coming from.

I ran your benchmark and see that, as provided, it seems to optimise the baseline code out. Making sure the failed/ passed variables are used fixes that - but there's still a larger difference between a Catch2 assertion and the direct code than I'd like.
I've also narrowed it down to the same `AssertionHandler::handle` overload that @horenmar cited.

What I haven't done, yet, is compare it against Catch 1.x - to see if there really is a large regression.

**Comment by philsquared** [comment] 2017-11-10 08:41
I have actually not done the v1 vs v2 compare, and it does seem to match your findings :-(
Still trying to home in on what key difference is.

**Comment by philsquared** [comment] 2017-11-10 08:42
Argh! s/not/now/

**Comment by horenmar** [comment] 2018-02-10 13:37
After the discussion and changes from the associated PR's the performance of Catch2 should be better than Catch Classic's , so I am going to close this issue.

If you have further suggestions in regards to performance, please open up a new issue.

**Closed by horenmar** 2018-02-10 13:37 UTC
