### ISSUE TITLE
One test fails: Error regular expression found in output. Regex=

### ISSUE THREAD

**Issue by yurivict** [catchorg/Catch2#1194] opened 2018-02-20 08:38 UTC
Getting this with version 2.1.2 on FreeBSD, with clang-40:

```
Running tests...
Test project /usr/ports/devel/catch2/work/.build
    Start 1: RunTests
1/6 Test #1: RunTests .........................   Passed    0.01 sec
    Start 2: ListTests
2/6 Test #2: ListTests ........................   Passed    0.00 sec
    Start 3: ListTags
3/6 Test #3: ListTags .........................   Passed    0.00 sec
    Start 4: ListReporters
4/6 Test #4: ListReporters ....................   Passed    0.00 sec
    Start 5: ListTestNamesOnly
5/6 Test #5: ListTestNamesOnly ................   Passed    0.00 sec
    Start 6: ApprovalTests
6/6 Test #6: ApprovalTests ....................***Failed  Error regular expression found in output. Regex=[Results differed]  1.08 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) =   1.12 sec
```

**Comment by horenmar** [comment] 2018-02-23 11:25
Can you rerun with verbose output?

Quick guess is that in FreeBSD's C library macros like `inf`, `NAN` expand into a currently unknown expression and thus aren't normalized.

**Comment by christoph-conrads** [comment] 2018-07-30 15:36
Catch2 v2.3.0, Linux Mint, g++ (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4, CMake 3.7.2.
The attachment contains the output of `ctest -V -R Approval --output-log ~/catch2.issue1194.txt`.

[catch2.issue1194.txt](https://github.com/catchorg/Catch2/files/2241802/catch2.issue1194.txt)

The error also occurs with Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4) (`-Werror` must be disabled).

**Comment by christoph-conrads** [comment] 2018-07-30 15:38
I am using an out-of-source build. Thus, maybe this is a duplicate of #1200.

**Closed** 2018-10-19 10:46 UTC
Labels: Possible bug
