### ISSUE TITLE
Some tags seem not to work

### ISSUE THREAD

**Issue by Japes** [catchorg/Catch2#1688] opened 2019-07-12 07:58 UTC
Hi,

I seem to be having an issue where certain tag names refuse to be run explicitly.

with these scenarios:
```
SCENARIO("A", "[A]")
{
	std::cout << "(" << __FUNCTION__ << ") A" << std::endl;
}

SCENARIO("B", "[status_var]")
{
	std::cout << "(" << __FUNCTION__ << ") B" << std::endl;
}

```

I get the following output:

```
$ my_test_executable [A]
Filters: [A]
(____C_A_T_C_H____T_E_S_T____0) A
===============================================================================
test cases: 1 | 1 passed
assertions: - none -


$ my_test_executable [status_var]
Filters: a
===============================================================================
No tests ran

```

Seems like it's something to do with the tag parsing, since the "Filters:" printout is wrong as well.  

2 others that also don't seem to work are `BMCA_sync_var` and `BMCA_sync_ffa`

thanks

**Comment by horenmar** [comment] 2019-07-13 14:18
Can't reproduce this

```
$ ./a.out [A]
Filters: [A]
(____C_A_T_C_H____T_E_S_T____0) A
===============================================================================
test cases: 1 | 1 passed
assertions: - none -

$ ./a.out [status_var]
Filters: [status_var]
(____C_A_T_C_H____T_E_S_T____2) B
===============================================================================
test cases: 1 | 1 passed
assertions: - none -
```

but I seem to remember a similar issue, where the problem was that the user's shell interpreted `[FOO]` as variable dereference -- are you using Bash or a different shell?

**Comment by Japes** [comment] 2019-07-18 14:11
Hi,

Using Bash.  Was on an older version, but upgraded to 2.9.1 and still have the issue.  Will investigate variable dereference theory.

**Comment by JoeyGrajciar** [comment] 2019-10-30 20:24
@Japes can't reproduce either.
Closing the issue.

**Closed by JoeyGrajciar** 2019-10-30 20:24 UTC
Labels: Can't reproduce
