### ISSUE TITLE
MSVC, release mode: Degrading compilation time with > 100 CHECKs

### ISSUE THREAD

**Issue by karyon** [catchorg/Catch2#1464] opened 2018-11-29 16:40 UTC
We had a test with 280 CHECKs and it took three minutes to compile. I did some testing, check this out:

![image](https://user-images.githubusercontent.com/1891915/49236768-1f2b3180-f3fd-11e8-928c-19ff90288082.png)

These are the compilation time of a single test case. This is visual studio 15.8 in release mode, in debug mode this does not happen. Almost all the time is spent in the compiler backend (c2.dll). the FAST_COMPILE switch did not change anything. This does not happen in a really old (1.0) version of catch.

Any suggestions? I can spend some more time on investigating, if there are any open questions.

**Comment by karyon** [comment] 2018-11-30 13:38
That was without LTCG. with /LTCG and /GL, the problem moved to link time (surprise :) ), and code generation was actually a few seconds faster (but not substantially) for that function.

**Comment by horenmar** [comment] 2018-11-30 15:12
Okay, I can reproduce your results, but for me the time required is a lot smaller, and, after a certain threshold, the compilation times start going down again.

From quick and dirty testing (I copy pasted the same `REQUIRE` n times and measured time reported by MSBuild):
*  200 assertions took ~14s to compile
*  400 assertions took ~50s to compile
*  600 assertions took ~140s to compile
*  800 assertions took ~10s to compile
* 1000 assertions took ~13s to compile
* 1200 assertions took ~18s to compile

At this point I think there are 2 things to do
1) Open up a bug with MS, because there is a quadratic optimization pass inside the compiler and it probably needs better heuristic to determine when it can be applied without blowing up compilation times
2) Investigate the use of "do not optimize this" MSVC pragmas inside Catch

**Comment by karyon** [comment] 2018-11-30 15:34
thanks for taking the time to look into this.

indeed putting a `#pragma optimize("", off)` around the problematic test case drops its compile time to a second. it might not be possible to use this inside the REQUIRE macro, when i tried to put it just around the REQUIRES inside the test case, i got an error that the pragma must be placed outside functions.

**Comment by onqtam** [comment] 2018-12-01 10:57
I've encountered this problem with the MSVC optimizer a few years ago - the problem occurs when there are many branches, and it gets worse quite quickly (I don't remember there being an upper bound).

I don't see a solution to this since the normal asserts of Catch have a single branch in them (in the expanded code in the test cases) and you cannot get any better than that (that branch is for breaking into the debugger). Actually you could try using [CATCH_CONFIG_FAST_COMPILE](https://github.com/catchorg/Catch2/blob/master/docs/configuration.md#catch_config_fast_compile) but I think it only removes the try/catch sections around the evaluation of expressions in asserts (exceptions are still caught by the test runner if the test case is aborted by such)

**Comment by karyon** [comment] 2018-12-17 09:15
@horenmar just to make sure, you didn't create a bug report by any chance? i'd do that today if there's no reason not to do it.

**Comment by karyon** [comment] 2018-12-17 09:36
....could you send me the code you used to repro this? or tell me what you did? just now i didn't manage to repro this with a very simple example project.

**Comment by horenmar** [comment] 2018-12-18 16:47
There is no bug report -- I had some backchannel talks with MSVC and was told to open a bug for it, but some real-world stuff came up and I didn't have time to finish writing it up.

Anyway, I just tried to reproduce it, and the set up that previously ran into 2 minute+ compilation times finishes up in 300ms, so I am gonna call it fixed by 15.9.4 update.

**Comment by karyon** [comment] 2018-12-20 11:50
I tried again reproducing this and managed to do it with 15.9.4 and the following code:
```c++
#include "catch.hpp"

#include <string>

struct SomeClass {
    SomeClass bar() {
        return SomeClass();
    }

    std::string foo() {
        return "foo";
    }
};

TEST_CASE("foo is bar") {
    CHECK(SomeClass().bar().foo() == "bar");
    // < repeat 300 times>
}
```
compiles in 40 seconds.
if i try to remove the call to the constructor or bar, the compilation time is just a few seconds.

shall i open a bug report with this or do you want to do that?

**Comment by horenmar** [comment] 2018-12-20 19:17
@karyon If you are willing to do it, I'll gladly leave handling the bug report to you.

**Comment by karyon** [comment] 2018-12-21 11:15
i created https://developercommunity.visualstudio.com/content/problem/414125/exponential-compilation-time-with-catch2-asserts.html. however, i did not actually try to reduce catch itself to a minimum. Let's see whether someone looks at it :)

**Comment by horenmar** [comment] 2019-01-18 14:44
@karyon Mind if I close this issue in the meantime?

**Closed** 2019-01-19 21:46 UTC
Labels: Resolved - pending review
